# -*- coding: utf-8 -*-
"""CÓDIGO_AMBRÓSIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOCtmrsWLl6rm6jAZaMBpf7fntscg57Y
"""

# @title
import getpass
import random

# --- NOVO: BANCO DE DADOS NA MEMÓRIA ---
# Dicionário para guardar usuários e senhas.
# Formato: { 'usuario': 'senha' }
banco_usuarios = {"Iza_Cuidadora": "Iza2025@",
    "admin": "admin"}

# ==============================================================================
# MÓDULO 1: LUCY (Relatórios)
# Função: Exibir relatórios baseados no turno
# ==============================================================================
def acessar_relatorios_lucy():
    print("\n--- RELATÓRIOS (Módulo Lucy) ---")
    print("1 - Manhã")
    print("2 - Tarde")
    print("3 - Noite")

    op = input("Escolha o turno: ")

    if op == "1":
        print("\nManhã: ")
        print("- Acordar o idoso")
        print("- Higiene e troca de roupas")
        print("- Café da manhã")
        print("- Medicamentos")
    elif op == "2":
        print("\nTarde:")
        print(" - Almoço")
        print(" - Higiene bucal")
        print(" - Descanso")
        print(" - Lanche e banho")
    elif op == "3":
        print("\nNoite:")
        print(" - Jantar leve")
        print("- Preparar para dormir!")
    else:
        print("Opção inválida")

    input("\nPressione ENTER para voltar...")

# ==============================================================================
# MÓDULO 2: KARINE (Área do Cuidador)
# Função: Gerenciar tarefas e chamar relatórios
# ==============================================================================
def menu_cuidador_karine():
    print("\n=== BEM-VINDO CUIDADOR (Módulo Karine) ===")

    # Listas locais para armazenar dados enquanto o programa roda
    tarefas = []

    opcoes = " "
    while opcoes != "0":
        print("\nEscolha uma opção abaixo:")
        print("1. Ver tarefas")
        print("2. Ver necessidades")
        print("3. Ver lembretes")
        print("4. Acessar relatórios")
        print("0. Sair (Logout)")

        opcoes = input("Digite a opção desejada: ").strip()

        if opcoes == "1":
            subtarefa = ""
            while subtarefa != "0":
                print("\n--- MENU DE TAREFAS ---")
                print("1. Adicionar tarefa")
                print("2. Listar tarefas")
                print("3. Remover tarefa")
                print("0. Voltar")

                subtarefa = input("\nEscolha uma opção: ")

                if subtarefa == "1":
                    nova = input("\nDigite a nova tarefa: ")
                    tarefas.append(nova)
                    print("✔ Tarefa adicionada com sucesso!")

                elif subtarefa == "2":
                    print("\n--- Lista de tarefas ---")
                    if len(tarefas) == 0:
                        print("Nenhuma tarefa cadastrada.")
                    else:
                        for i, t in enumerate(tarefas):
                            print(f"{i+1}. {t}")

                elif subtarefa == "3":
                    print("\n--- REMOVER TAREFA ---")
                    if len(tarefas) == 0:
                        print("Não há tarefas para remover.")
                    else:
                        for i, t in enumerate(tarefas):
                            print(f"{i+1}. {t}")
                        try:
                            remover = int(input("Digite o número da tarefa para remover: "))
                            if 1 <= remover <= len(tarefas):
                                tarefas.pop(remover - 1)
                                print("✔ Tarefa removida!")
                            else:
                                print("Número inválido.")
                        except ValueError:
                            print("Entrada inválida.")

                elif subtarefa == "0":
                    print("Voltando...")

        elif opcoes == "2":
            print("\n(Funcionalidade de Necessidades em construção)")

        elif opcoes == "3":
            print("\n(Funcionalidade de Lembretes em construção)")

        elif opcoes == "4":
            # AQUI ESTÁ A INTEGRAÇÃO: Karine chama o código da Lucy
            acessar_relatorios_lucy()

        elif opcoes == "0":
            print("\nFazendo logout do cuidador...")
            break
        else:
            print("Opção inválida")

# ==============================================================================
# MÓDULO 3: DANI (Área do Idoso)
# Função: Painel simplificado para o idoso
# ==============================================================================
def menu_idoso_dani():
    print("\n=== BEM-VINDO IDOSO (Módulo Dani) ===")
    nome = input("Confirme seu nome: ")
    print(f"Olá, {nome}!")

    # Loop simples para o menu do idoso não fechar na hora
    while True:
        print("\n1. Adicionar Tarefa/Lembrete")
        print("2. Sair")
        escolha = input("Escolha: ")

        if escolha == "1":
            nome_tarefa = input("\nDigite o nome da tarefa: ")
            try:
                hora = float(input("Digite a hora (ex: 14.30): "))
                if hora < 12:
                    print("Cuidado será pela manhã.")
                elif 12 <= hora < 18:
                    print("Cuidado será à tarde.")
                elif 18 <= hora < 24:
                    print("Cuidado será à noite.")
                else:
                    print("Hora inválida.")
            except ValueError:
                print("Por favor, digite um número para a hora.")

            print(f"Tarefa '{nome_tarefa}' registrada.")
            input("Enter para continuar...")

        elif escolha == "2":
            break

# ==============================================================================
# MÓDULO 4: IZA (Login)
# Função: Autenticação. Retorna True se funcionou, False se falhou.
# ==============================================================================
def realizar_login_iza():
    # Dados simulados
    USUARIO_CORRETO = "Iza_Cuidadora"
    SENHA_CORRETA = "Iza2025@"
    EMAIL_CADASTRADO = "usuario@exemplo.com"

    tentativas = 0
    limite_tentativas = 2

    while True:
        print("\n=== LOGIN (Módulo Iza) ===")
        print(f"(Dica para teste: Usuário: {USUARIO_CORRETO} | Senha: {SENHA_CORRETA})")

        usuario = input("Digite seu usuário: ")
        # Se der erro no getpass no seu computador, troque por input() simples
        try:
            senha = getpass.getpass("Digite sua senha: ")
        except:
            senha = input("Digite sua senha: ")

        if usuario == USUARIO_CORRETO and senha == SENHA_CORRETA:
            print("\nLogin bem-sucedido! Bem-vindo!")
            return True # Retorna SUCESSO para o menu principal

        else:
            tentativas += 1
            print("\nUsuário ou senha incorretos.")

            if tentativas < limite_tentativas:
                print(f"Tentativas restantes: {limite_tentativas - tentativas}")
            else:
                print("\nVocê atingiu o limite de tentativas.")
                escolha = input("Esqueceu a senha? Digite 'sim' para recuperar: ").strip().lower()

                if escolha == "sim":
                    print(f"\nEnviando código para {EMAIL_CADASTRADO}...")
                    codigo_enviado = str(random.randint(100000, 999999))
                    print(f"(Simulação - código gerado: {codigo_enviado})")

                    codigo_digitado = input("Digite o código recebido: ")

                    if codigo_digitado == codigo_enviado:
                        print("\nCódigo correto!")
                        nova_senha = input("Digite sua nova senha: ")
                        SENHA_CORRETA = nova_senha
                        print("Senha redefinida! Tente logar novamente.\n")
                        tentativas = 0
                    else:
                        print("Código incorreto! Tente novamente.")
                else:
                    return False # Falhou e desistiu

# ==============================================================================
# MÓDULO 5: ELVIS (Menu Principal / Sistema Central)
# Função: Controla o início de tudo
# ==============================================================================

def exibir_menu_elvis():
    print("\n=== AMBROSIA ===")
    print("Sistema de Atendimento ao Idoso\n")
    print("1. Quem Somos?")
    print("2. Login")
    print("3. Cadastre-se")
    print("0. Sair do Sistema\n")
    return input("Digite uma opção: ")

def quem_somos_elvis():
    print("\n=== Quem Somos? ===")
    print("O Ambrósia nasceu com o próposito de transformar a forma como cuidamos da população idosa." \
    " Acreditamos que cuidar é um ato de amor, e por isso, desenvolvemos uma solução que une tecnologia, empatia e simplicidade, permitindo que profissionais de saúde, cuidadores e familiares acompanhem o bem-estar dos idosos de forma integrada." \
    "Nosso sistema foi pensado com base em experiências reais, refletindo a humanização no atendimento, a valorização da história de vida dos idosos e o desejo de garantir mais conforto, autonomia e dignidade." \
    " Inspirado por uma geração que tanto fez por nós,o Ambrósia é um gesto de retribuição.")
    print("(Texto institucional...)")
    input("Pressione ENTER para voltar...")

def tela_cadastro_elvis():
    print("\n=== CADASTRO ===")
    print("1. Sou cuidador")
    print("2. Preciso de cuidado")
    opcao = input("Escolha: ")
    if opcao == "1":
        print("Cadastro de cuidador em construção...")
    elif opcao == "2":
        print("Iniciando cadastro de paciente...")
        # Aqui poderia chamar a lógica de cadastro
    input("Enter para voltar...")

# --- EXECUÇÃO PRINCIPAL ---
def iniciar_sistema():
    while True:
        escolha = exibir_menu_elvis()

        if escolha == "1":
            quem_somos_elvis()

        elif escolha == "2":
            # Chama o Login da Iza
            login_sucesso = realizar_login_iza()

            if login_sucesso:
                # SE O LOGIN DEU CERTO, DIRECIONA:
                print("\n--- SELEÇÃO DE PERFIL ---")
                print("1. Acessar como Cuidador")
                print("2. Acessar como Idoso")
                perfil = input("Escolha seu perfil: ")

                if perfil == "1":
                    menu_cuidador_karine() # Chama Karine
                elif perfil == "2":
                    menu_idoso_dani() # Chama Dani
                else:
                    print("Perfil inválido.")

        elif escolha == "3":
            tela_cadastro_elvis()

        elif escolha == "0":
            print("Saindo do sistema Ambrósia. Até logo!")
            break

        else:
            print("\nOpção inválida.")

# ==============================================================================
# PONTO DE PARTIDA (Start)
# ==============================================================================
if __name__ == "__main__":
    iniciar_sistema()

import getpass
import random

# ==============================================================================
# BANCO DE DADOS
# Aqui ficam salvos todos os usuários.
# ==============================================================================
banco_usuarios = {
    "Iza_Cuidadora": "Iza2025@",
    "admin": "admin"
}

# ==============================================================================
# Relatórios
# ==============================================================================
def acessar_relatorios_lucy():
    print("\n--- RELATÓRIOS (Módulo Lucy) ---")
    print("1 - Manhã")
    print("2 - Tarde")
    print("3 - Noite")

    op = input("Escolha o turno: ")

    if op == "1":
        print("\nManhã: ")
        print("- Acordar o idoso")
        print("- Higiene e troca de roupas")
        print("- Café da manhã")
        print("- Medicamentos")
    elif op == "2":
        print("\nTarde:")
        print(" - Almoço")
        print(" - Higiene bucal")
        print(" - Descanso")
        print(" - Lanche e banho")
    elif op == "3":
        print("\nNoite:")
        print(" - Jantar leve")
        print("- Preparar para dormir!")
    else:
        print("Opção inválida")

    input("\nPressione ENTER para voltar...")

# ==============================================================================
# Área do Cuidador
# ==============================================================================
def menu_cuidador_karine():
    print("\n=== BEM-VINDO CUIDADOR (Módulo Karine) ===")
    tarefas = []

    opcoes = " "
    while opcoes != "0":
        print("\nEscolha uma opção abaixo:")
        print("1. Ver tarefas")
        print("2. Ver necessidades")
        print("3. Ver lembretes")
        print("4. Acessar relatórios")
        print("0. Sair (Logout)")

        opcoes = input("Digite a opção desejada: ").strip()

        if opcoes == "1":
            subtarefa = ""
            while subtarefa != "0":
                print("\n--- MENU DE TAREFAS ---")
                print("1. Adicionar tarefa")
                print("2. Listar tarefas")
                print("3. Remover tarefa")
                print("0. Voltar")

                subtarefa = input("\nEscolha uma opção: ")

                if subtarefa == "1":
                    nova = input("\nDigite a nova tarefa: ")
                    tarefas.append(nova)
                    print("✔ Tarefa adicionada com sucesso!")

                elif subtarefa == "2":
                    print("\n--- Lista de tarefas ---")
                    if len(tarefas) == 0:
                        print("Nenhuma tarefa cadastrada.")
                    else:
                        for i, t in enumerate(tarefas):
                            print(f"{i+1}. {t}")

                elif subtarefa == "3":
                    print("\n--- REMOVER TAREFA ---")
                    if len(tarefas) == 0:
                        print("Não há tarefas para remover.")
                    else:
                        for i, t in enumerate(tarefas):
                            print(f"{i+1}. {t}")
                        try:
                            remover = int(input("Digite o número da tarefa para remover: "))
                            if 1 <= remover <= len(tarefas):
                                tarefas.pop(remover - 1)
                                print("✔ Tarefa removida!")
                            else:
                                print("Número inválido.")
                        except ValueError:
                            print("Entrada inválida.")

                elif subtarefa == "0":
                    print("Voltando...")

        elif opcoes == "2":
            print("\n(Funcionalidade de Necessidades em construção)")
        elif opcoes == "3":
            print("\n(Funcionalidade de Lembretes em construção)")
        elif opcoes == "4":
            acessar_relatorios_lucy() # Integração com Lucy
        elif opcoes == "0":
            print("\nFazendo logout do cuidador...")
            break
        else:
            print("Opção inválida")

# ==============================================================================
#  Área do Idoso
# ==============================================================================
def menu_idoso_dani():
    print("\n=== BEM-VINDO IDOSO (Módulo Dani) ===")
    nome = input("Confirme seu nome: ")
    print(f"Olá, {nome}!")

    while True:
        print("\n1. Adicionar Tarefa/Lembrete")
        print("2. Sair")
        escolha = input("Escolha: ")

        if escolha == "1":
            nome_tarefa = input("\nDigite o nome da tarefa: ")
            try:
                hora = float(input("Digite a hora (ex: 14.30): "))
                if hora < 12:
                    print("Cuidado será pela manhã.")
                elif 12 <= hora < 18:
                    print("Cuidado será à tarde.")
                elif 18 <= hora < 24:
                    print("Cuidado será à noite.")
                else:
                    print("Hora inválida.")
            except ValueError:
                print("Por favor, digite um número para a hora.")

            print(f"Tarefa '{nome_tarefa}' registrada.")
            input("Enter para continuar...")

        elif escolha == "2":
            break

# ==============================================================================
#  Login
# ==============================================================================
def realizar_login_iza():
    tentativas = 0
    limite_tentativas = 3

    while True:
        print("\n=== LOGIN (Módulo Iza) ===")

        # Pede os dados
        usuario_input = input("Digite seu usuário: ").strip()
        try:
            senha_input = getpass.getpass("Digite sua senha: ")
        except:
            senha_input = input("Digite sua senha: ")

        # --- AQUI ESTÁ A LÓGICA DO DICIONÁRIO ---
        # Verifica se o usuário existe no dicionário E se a senha bate
        if usuario_input in banco_usuarios and banco_usuarios[usuario_input] == senha_input:
            print(f"\nLogin bem-sucedido! Bem-vindo, {usuario_input}!")
            return True # Sucesso

        else:
            tentativas += 1
            print("\n Usuário ou senha incorretos.")

            if tentativas >= limite_tentativas:
                print("\n Você atingiu o limite de tentativas.")
                return False # Falhou

# ==============================================================================
# (Menu Principal e CADASTRO)
# ==============================================================================

def cadastro_cuidador():
    print("\n=== CADASTRO DE CUIDADOR ===")

    # 1. Pede o login que a pessoa quer criar
    novo_usuario = input("Crie um nome de usuário (Login): ").strip()

    # 2. Verifica se já existe no dicionário
    if novo_usuario in banco_usuarios:
        print(" Esse usuário já existe! Tente outro.")
        return

    # 3. Pede a senha
    nova_senha = input("Crie uma senha: ")

    # 4. SALVA NO DICIONÁRIO
    banco_usuarios[novo_usuario] = nova_senha
    print(f"\n Cuidador cadastrado com sucesso! Agora você pode logar como '{novo_usuario}'.")
    input("Pressione ENTER para voltar...")

def cadastro_preciso_de_cuidado():
    print("\n=== CADASTRO DE IDOSO/PACIENTE ===")

    # Coleta dados pessoais (Visual apenas)
    nome = input("Nome completo: ")
    nasc = input("Data de nascimento: ")
    cpf = input("CPF: ")

    print("\n--- Criação de Acesso ---")
    # 1. Pede o login
    novo_usuario = input("Crie um nome de usuário para entrar no sistema: ").strip()

    # 2. Verifica se já existe
    if novo_usuario in banco_usuarios:
        print(" Esse usuário já existe! Tente outro.")
        return

    # 3. Pede a senha
    nova_senha = input("Crie uma senha: ")

    # 4. SALVA NO DICIONÁRIO
    banco_usuarios[novo_usuario] = nova_senha

    print(f"\n Cadastro realizado! Usuário '{novo_usuario}' salvo no sistema.")
    input("Pressione ENTER para voltar...")

def tela_cadastro_elvis():
    print("\n=== TELA DE CADASTRO ===")
    print("1. Sou cuidador")
    print("2. Preciso de cuidado")
    print("0. Voltar")

    opcao = input("Escolha: ")

    if opcao == "1":
        cadastro_cuidador()
    elif opcao == "2":
        cadastro_preciso_de_cuidado()
    elif opcao == "0":
        return
    else:
        print("Opção inválida.")

def exibir_menu_elvis():
    print("\n=== AMBROSIA ===")
    print("Sistema de Atendimento ao Idoso\n")
    print("1. Quem Somos?")
    print("2. Login")
    print("3. Cadastre-se")
    print("0. Sair do Sistema\n")
    return input("Digite uma opção: ")

def quem_somos_elvis():
    print("\n=== Quem Somos? ===")
    print("O Ambrósia nasceu com o propósito de transformar a forma como cuidamos...")
    input("Pressione ENTER para voltar...")

# --- EXECUÇÃO PRINCIPAL ---
def iniciar_sistema():
    while True:
        escolha = exibir_menu_elvis()

        if escolha == "1":
            quem_somos_elvis()

        elif escolha == "2":
            # Chama o Login da Iza
            login_sucesso = realizar_login_iza()

            if login_sucesso:
                print("\n--- SELEÇÃO DE PERFIL ---")
                print("1. Entrar no Painel do Cuidador")
                print("2. Entrar no Painel do Idoso")
                perfil = input("Escolha seu perfil: ")

                if perfil == "1":
                    menu_cuidador_karine()
                elif perfil == "2":
                    menu_idoso_dani()
                else:
                    print("Perfil inválido.")

        elif escolha == "3":
            # Chama o cadastro novo que salva no dicionário
            tela_cadastro_elvis()

        elif escolha == "0":
            print("Saindo do sistema Ambrósia. Até logo!")
            break

        else:
            print("\nOpção inválida.")

# ==============================================================================
# PONTO DE PARTIDA (Start)
# ==============================================================================
if __name__ == "__main__":
    iniciar_sistema()